### ISSUE TITLE
Responsive fixes needed

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/PranayRanjanWeb#2]
The mobile view is not responsible:

Fixes/Bugs:
1. The timeline section on hover should not be there in phone view.
2. The images animations needs to be removed on phone view.
3. The headline in landing should be centered aligned on phone view.

**Comment by Joshuafolorunsho** [comment]
I can work on this

**Comment by Joshuafolorunsho** [comment]
Can you assign me to this? @harshgoel05

**Comment by harshgoel05** [comment]
Sure go ahead! @Joshuafolorunsho

**Comment by Joshuafolorunsho** [comment]
I have fixed the first and second one. The third one. Which of the heading do you want to be centered on mobile view? @harshgoel05

**Comment by harshgoel05** [comment]
The first screen which shows the name and the tagline must be vertically center of the phone.

Feel free to add any other improvements if you want to. 😄🤞

**Comment by Joshuafolorunsho** [comment]
I deleted the comment. I now understand. Thanks for the clarification. Looks better now

![image](https://user-images.githubusercontent.com/55793353/94799805-9e179980-03db-11eb-826e-4826587e755a.png)

**Comment by harshgoel05** [comment]
Yeah cool. This looks amazing.

**Comment by Joshuafolorunsho** [comment]
I have opened a pull request

**Comment by harshgoel05** [comment]
Cool!
